### ISSUE TITLE
Module "crypto" has been externalized for browser compatibility.

### ISSUE THREAD

**Issue by madebyfabian** [TwicPics/url#36]
Using this package in a Nuxt 3 project, next to the @twicpics/components. When using on the client, I get this vite warning:

```bash
Module "crypto" has been externalized for browser compatibility. Cannot access "crypto.createCipheriv" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

Essentially this is caused because this module does import crypto as module at here:

https://github.com/search?q=repo%3ATwicPics%2Furl%20crypto&type=code

Which is not allowed in browsers, since there is `window.crypto`. Therefore this module require must only happen on the server.

**Comment by madebyfabian** [comment]
I see the warning that this module is server-side. Interestingly it works on client-side too besides that error.

**Comment by jaubourg** [comment]
Hey @madebyfabian,

I suppose most of the API will work but I strongly suspect the `multiple()` method will fail because of its use of NodeJS `Buffer`. We'll look into having it work client-side at some point.
